In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("../Dataset/customer_churn_prediction_dataset.csv")

In [8]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0001-XXXX,Male,0,Yes,Yes,5,No,Yes,No,No,...,No,No,No,No internet service,Month-to-month,Yes,Credit card,27.43,137.15,Yes
1,0002-XXXX,Female,0,No,No,42,Yes,No phone service,DSL,Yes,...,No,No,No internet service,No internet service,Two year,No,Electronic check,38.28,1607.76,Yes
2,0003-XXXX,Male,0,No,No,61,Yes,No phone service,No,No,...,No,Yes,Yes,No,One year,No,Bank transfer,106.44,6492.84,Yes
3,0004-XXXX,Male,1,No,Yes,22,Yes,No,No,No internet service,...,Yes,No,No internet service,Yes,Month-to-month,No,Electronic check,92.49,2034.78,No
4,0005-XXXX,Male,1,Yes,Yes,21,No,No,DSL,No,...,No internet service,No,No,No internet service,One year,No,Bank transfer,19.63,412.23,Yes

Creating Churn flag

In [13]:
df['churn_flag']=(df['Churn']=='Yes').astype(int)

In [14]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,churn_flag
0,0001-XXXX,Male,0,Yes,Yes,5,No,Yes,No,No,...,No,No,No internet service,Month-to-month,Yes,Credit card,27.43,137.15,Yes,1
1,0002-XXXX,Female,0,No,No,42,Yes,No phone service,DSL,Yes,...,No,No internet service,No internet service,Two year,No,Electronic check,38.28,1607.76,Yes,1
2,0003-XXXX,Male,0,No,No,61,Yes,No phone service,No,No,...,Yes,Yes,No,One year,No,Bank transfer,106.44,6492.84,Yes,1
3,0004-XXXX,Male,1,No,Yes,22,Yes,No,No,No internet service,...,No,No internet service,Yes,Month-to-month,No,Electronic check,92.49,2034.78,No,0
4,0005-XXXX,Male,1,Yes,Yes,21,No,No,DSL,No,...,No,No,No internet service,One year,No,Bank transfer,19.63,412.23,Yes,1

Removing unwanted features

In [15]:
df.drop(columns=['customerID','Churn'],inplace=True)

In [16]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,churn_flag
0,Male,0,Yes,Yes,5,No,Yes,No,No,Yes,No,No,No,No internet service,Month-to-month,Yes,Credit card,27.43,137.15,1
1,Female,0,No,No,42,Yes,No phone service,DSL,Yes,Yes,No,No,No internet service,No internet service,Two year,No,Electronic check,38.28,1607.76,1
2,Male,0,No,No,61,Yes,No phone service,No,No,Yes,No,Yes,Yes,No,One year,No,Bank transfer,106.44,6492.84,1
3,Male,1,No,Yes,22,Yes,No,No,No internet service,No internet service,Yes,No,No internet service,Yes,Month-to-month,No,Electronic check,92.49,2034.78,0
4,Male,1,Yes,Yes,21,No,No,DSL,No,No,No internet service,No,No,No internet service,One year,No,Bank transfer,19.63,412.23,1

In [17]:
df['tenure_bucket']=pd.cut(
    df['tenure'],
    bins=[0,6,12,24,48,max(df['tenure'])],
    labels=['0-6','6-12','12-24','24-48','49+'],
    include_lowest=True
)

In [18]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,churn_flag,tenure_bucket
0,Male,0,Yes,Yes,5,No,Yes,No,No,Yes,...,No,No,No internet service,Month-to-month,Yes,Credit card,27.43,137.15,1,0-6
1,Female,0,No,No,42,Yes,No phone service,DSL,Yes,Yes,...,No,No internet service,No internet service,Two year,No,Electronic check,38.28,1607.76,1,24-48
2,Male,0,No,No,61,Yes,No phone service,No,No,Yes,...,Yes,Yes,No,One year,No,Bank transfer,106.44,6492.84,1,49+
3,Male,1,No,Yes,22,Yes,No,No,No internet service,No internet service,...,No,No internet service,Yes,Month-to-month,No,Electronic check,92.49,2034.78,0,12-24
4,Male,1,Yes,Yes,21,No,No,DSL,No,No,...,No,No,No internet service,One year,No,Bank transfer,19.63,412.23,1,12-24

Dropping Total Charges as it is highly correlated with tenure

In [19]:
df.drop(columns='TotalCharges',inplace=True)

In [20]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,churn_flag,tenure_bucket
0,Male,0,Yes,Yes,5,No,Yes,No,No,Yes,No,No,No,No internet service,Month-to-month,Yes,Credit card,27.43,1,0-6
1,Female,0,No,No,42,Yes,No phone service,DSL,Yes,Yes,No,No,No internet service,No internet service,Two year,No,Electronic check,38.28,1,24-48
2,Male,0,No,No,61,Yes,No phone service,No,No,Yes,No,Yes,Yes,No,One year,No,Bank transfer,106.44,1,49+
3,Male,1,No,Yes,22,Yes,No,No,No internet service,No internet service,Yes,No,No internet service,Yes,Month-to-month,No,Electronic check,92.49,0,12-24
4,Male,1,Yes,Yes,21,No,No,DSL,No,No,No internet service,No,No,No internet service,One year,No,Bank transfer,19.63,1,12-24

Separating out features and target

In [21]:
X=df.drop(columns=['churn_flag'])
y=df['churn_flag']

Encode categorical features

In [22]:
X=pd.get_dummies(X, drop_first=True)

In [23]:
X

,SeniorCitizen,tenure,MonthlyCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,...,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_bucket_6-12,tenure_bucket_12-24,tenure_bucket_24-48,tenure_bucket_49+
0,0,5,27.43,True,True,True,False,False,True,False,...,False,False,True,True,False,False,False,False,False,False
1,0,42,38.28,False,False,False,True,True,False,False,...,False,True,False,False,True,False,False,False,True,False
2,0,61,106.44,True,False,False,True,True,False,False,...,True,False,False,False,False,False,False,False,False,True
3,1,22,92.49,True,False,True,True,False,False,False,...,False,False,False,False,True,False,False,True,False,False
4,1,21,19.63,True,True,True,False,False,False,False,...,True,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1,61,42.52,False,False,True,False,False,True,False,...,True,False,True,False,True,False,False,False,False,True
296,0,49,22.31,False,False,False,True,True,False,False,...,False,False,True,False,False,True,False,False,False,True
297,0,71,59.57,True,False,True,True,False,True,False,...,False,True,False,False,False,True,False,False,False,True
298,1,1,31.32,True,True,True,True,False,True,False,...,False,True,False,True,False,False,False,False,False,False
299,1,13,20.50,False,True,True,True,False,True,False,...,False,False,False,False,True,False,False,True,False,False